# Generated by Django 5.2.4 on 2025-07-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_userprofile_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='keyword_limit',
            new_name='keyword_quota',
        ),
    ]
