# Generated by Django 5.2.4 on 2025-07-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_keyword_limit_userprofile_keyword_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordsearch',
            name='last_refreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
