# Generated by Django 5.2.4 on 2025-07-17 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_keywordsearch_last_refreshed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keywordsearch',
            unique_together={('user', 'keyword')},
        ),
    ]
