# Generated by Django 5.2.4 on 2025-07-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_keywordsearch_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keywordsearch',
            unique_together=set(),
        ),
    ]
